---
- name: Update the apt package index
  apt:
    update_cache: yes

- name: Install prerequisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get the distribution codename (lsb_release -cs)
  command: lsb_release -cs
  register: lsb_release
  changed_when: false

- name: Set up the stable repository for Docker installation
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - ensure docker is enabled and running

- name: Add user to the Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes